repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.103.0
    hooks:
    - id: terraform_fmt
      files: \.(tf|tfvars|hcl)$
    - id: terraform_validate
      files: \.(tf|tfvars|hcl)$
    - id: terraform_tflint
      files: \.(tf|tfvars|hcl)$
    - id: terraform_docs
      files: (\.tf|\.tfvars|\.hcl|Terraform/README\.md)$
    - id: terraform_trivy
      files: \.(tf|tfvars|hcl)$
